#!/bin/bash

getWebEnv(){ #Este metodo vai encontrar o WebEnv do historico do API
	Wenv=$(wget https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi\?db\=$1\&term\="$2"\&usehistory\=y\&retmax=100 -O - |grep -i "<WebEnv>"|sed 's/<[^<>]*>//g'|sed 's/.*_//') #| sed 's/[^0-9]//g'
	echo MCID_$Wenv # > /home/valente/Desktop/ASB
	return
}


getQueryKey(){ #Este metodo vai encontrar o QueryKey do historico do API
	QKey=$(wget https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi\?db\=$1\&term\="$2"\&usehistory\=y\&retmax=100 -O - |grep -i "<QueryKey>"|sed 's/<[^<>]*>//g'|sed 's/_*.//'|sed 's/M.*//'|rev |sed -r 's/(.{1}).*/\1/'|rev)
	echo $QKey # > /home/valente/Desktop/ASB
	return
}


webEnv=$(getWebEnv $1 "$2")
queryKey=$(getQueryKey $1 "$2")

getFasta(){ #Este metodo vai fazer o Efetch com os dados obtidos nos metodos anteriores.
	eFetch=$(wget https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi/\?db\=$1\&usehistory\=y\&query_key\=$queryKey\&WebEnv\=$webEnv\&rettype\=fasta -O ~/Downloads/Search.fasta)
	echo $eFetch
	return
}

fasta=$(getFasta $1 "$2")
echo $fasta
#cat ~/Search.fasta
#rm ~/Search.fasta

#------------------------------------------------------------------------------------------------------------
# Creates the file "Search.fasta" at the Downloads folder.
# This file is the raw download and is not yet sequenced.
#------------------------------------------------------------------------------------------------------------
# Sequencing "Search.fasta"
mafft ~/Downloads/Search.fasta > ~/Documents/Aligned-Search.fasta
rm ~/Downloads/Search.fasta
#------------------------------------------------------------------------------------------------------------
# Now we no longer have any file at the Downloads folder.
# Instead have the aligned sequence at Documents saved as "Aligned-Search.fasta"
#------------------------------------------------------------------------------------------------------------
sed "s/>.*: />/" ~/Documents/Aligned-Search.fasta > ~/Documents/Aligned-fSearch.fasta
rm ~/Documents/Aligned-Search.fasta
#------------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------------
